#!/bin/sh

### BEGIN INIT INFO
# Provides:             mpddns
# Required-Start:       $syslog $network $local_fs
# Required-Stop:        $syslog $network $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    mpddns
# Description:          A small dynamic DNS
### END INIT INFO

PATH=/bin:/usr/bin:/usr/local/sbin

NAME=mpddns
DAEMON=/opt/mpddns/server/mpddns.py
DAEMON_ARGS="-c /etc/mpddns/mpddns.conf"
PIDFILE=/var/run/mpddns.pid

. /lib/lsb/init-functions

case "$1" in

    start)
        log_daemon_msg "Starting ${NAME}"
        start_daemon -p $PIDFILE $DAEMON $DAEMON_ARGS
        log_end_msg 0
        ;;

    stop)
        log_daemon_msg "Stopping ${NAME}"
        killproc -p $PIDFILE $DAEMON
        log_end_msg 0
        ;;

    restart)
        log_daemon_msg "Restarting ${NAME}"
        killproc -p $PIDFILE $DAEMON
        sleep 1
        start_daemon -p $PIDFILE $DAEMON $DAEMON_ARGS
        log_end_msg 0
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;

esac

exit 0
